### PR TITLE
Support individual config keys in pillar yaml

### PR DESCRIPTION
**Pull request by vin01**
__Upside__: Pillar items are individually configurable, following YAML syntax and also allowing GPG encryption of individual items which can be very handy when used with Salt's GPG Renderer.

__Downside__: Comments will be lost from the config file :( although they can be maintained in pillar file.

### CODE REVIEW

**Comment by chr4** [comment]
Hey, thanks for the pull request!

I apprechiate the approach, but I'm a little worried that options might get lost due to this. e.g. there might be more than just `pages_external_url` and `external_url` as primary configuration targets... But this seems to be hard to abstract? 

Maybe something like "if this is a `dict`, then iterate and resolve as `dict['key'] = 'value'`, if not then use a `key = value` approach.

Does this differenciate different types correctly, e.g. ints and strings?

```ruby
dict['key'] = 1
dict['key'] = false
dict['key'] = 'value'
```

I'm also not sure whether there are (or could be) nested dictionaries, like so: `dict['key']['key2'] = 'value'`?

Theoretically, as this is ruby, this would also break code segments to configure special cases, but that might be ignored here I think...

**Comment by vin01** [comment]
Added a check for integer and strings.

I think for non integer, string types, generic value as-it-is from yaml shall work fine, like for nginx bind in the example pillar. Tried it with a dry run of salt.

**Comment by chr4** [comment]
Mmh, checking [gitlab.rb](https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/files/gitlab-config-template/gitlab.rb.template), there's some other cases to mind:

1. Values can be arrays: `roles ['redis_sentinel_role', 'redis_master_role']`
2. Hashes can be nested: `gitlab_rails['content_security_policy']['enabled'] = false`

**Comment by vin01** [comment]
yeah, also looks like much more cases are possible: https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/files/gitlab-config-template/gitlab.rb.template#L1348 :( 

Even if we use the official template itself, making it configurable via pillars would be a challenge for all these cases.

**Pull request closed without merging**
